/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team1Project;

/**
 *
 * @author CDfain
 */
public class DaGUI extends javax.swing.JFrame {
    private Team1Project Dot = new Team1Project();
    
    /**
     * Creates new form DaGUI
     */
    public DaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        generateButton = new javax.swing.JButton();
        redSwitch = new javax.swing.JPanel();
        redActivated = new javax.swing.JRadioButton();
        redDeactivated = new javax.swing.JRadioButton();
        orangeSwitch = new javax.swing.JPanel();
        orangeActivated = new javax.swing.JRadioButton();
        orangeDeactivated = new javax.swing.JRadioButton();
        yellowSwitch = new javax.swing.JPanel();
        yellowActivated = new javax.swing.JRadioButton();
        yellowDeactivated = new javax.swing.JRadioButton();
        greenSwitch = new javax.swing.JPanel();
        greenActivated = new javax.swing.JRadioButton();
        greenDeactivated = new javax.swing.JRadioButton();
        blueSwitch = new javax.swing.JPanel();
        blueDeactivated = new javax.swing.JRadioButton();
        blueActivated = new javax.swing.JRadioButton();
        violetSwitch = new javax.swing.JPanel();
        violetActivated = new javax.swing.JRadioButton();
        violetDeactivated = new javax.swing.JRadioButton();
        indegoSwitch = new javax.swing.JPanel();
        indegoActivated = new javax.swing.JRadioButton();
        indegoDeactivated = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileMenuLoad = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuCredits = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(redActivated);
        redActivated.setSelected(true);
        redActivated.setText("Red");

        buttonGroup1.add(redDeactivated);
        redDeactivated.setText("Red");
        redDeactivated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redDeactivatedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout redSwitchLayout = new javax.swing.GroupLayout(redSwitch);
        redSwitch.setLayout(redSwitchLayout);
        redSwitchLayout.setHorizontalGroup(
            redSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redSwitchLayout.createSequentialGroup()
                .addComponent(redActivated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(redDeactivated, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        redSwitchLayout.setVerticalGroup(
            redSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(redActivated)
                .addComponent(redDeactivated))
        );

        buttonGroup2.add(orangeActivated);
        orangeActivated.setSelected(true);
        orangeActivated.setText("Orange");
        orangeActivated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeActivatedActionPerformed(evt);
            }
        });

        buttonGroup2.add(orangeDeactivated);
        orangeDeactivated.setText("Orange");
        orangeDeactivated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeDeactivatedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orangeSwitchLayout = new javax.swing.GroupLayout(orangeSwitch);
        orangeSwitch.setLayout(orangeSwitchLayout);
        orangeSwitchLayout.setHorizontalGroup(
            orangeSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangeSwitchLayout.createSequentialGroup()
                .addComponent(orangeActivated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(orangeDeactivated, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        orangeSwitchLayout.setVerticalGroup(
            orangeSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangeSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(orangeActivated)
                .addComponent(orangeDeactivated))
        );

        buttonGroup3.add(yellowActivated);
        yellowActivated.setSelected(true);
        yellowActivated.setText("Yellow");

        buttonGroup3.add(yellowDeactivated);
        yellowDeactivated.setText("Yellow");

        javax.swing.GroupLayout yellowSwitchLayout = new javax.swing.GroupLayout(yellowSwitch);
        yellowSwitch.setLayout(yellowSwitchLayout);
        yellowSwitchLayout.setHorizontalGroup(
            yellowSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yellowSwitchLayout.createSequentialGroup()
                .addComponent(yellowActivated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yellowDeactivated, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        yellowSwitchLayout.setVerticalGroup(
            yellowSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yellowSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(yellowActivated)
                .addComponent(yellowDeactivated))
        );

        buttonGroup4.add(greenActivated);
        greenActivated.setSelected(true);
        greenActivated.setText("Green");
        greenActivated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActivatedActionPerformed(evt);
            }
        });

        buttonGroup4.add(greenDeactivated);
        greenDeactivated.setText("Green");
        greenDeactivated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenDeactivatedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout greenSwitchLayout = new javax.swing.GroupLayout(greenSwitch);
        greenSwitch.setLayout(greenSwitchLayout);
        greenSwitchLayout.setHorizontalGroup(
            greenSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenSwitchLayout.createSequentialGroup()
                .addComponent(greenActivated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(greenDeactivated, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        greenSwitchLayout.setVerticalGroup(
            greenSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(greenActivated)
                .addComponent(greenDeactivated))
        );

        buttonGroup5.add(blueDeactivated);
        blueDeactivated.setText("Blue");

        buttonGroup5.add(blueActivated);
        blueActivated.setSelected(true);
        blueActivated.setText("Blue");

        javax.swing.GroupLayout blueSwitchLayout = new javax.swing.GroupLayout(blueSwitch);
        blueSwitch.setLayout(blueSwitchLayout);
        blueSwitchLayout.setHorizontalGroup(
            blueSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueSwitchLayout.createSequentialGroup()
                .addComponent(blueActivated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(blueDeactivated, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        blueSwitchLayout.setVerticalGroup(
            blueSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(blueDeactivated)
                .addComponent(blueActivated))
        );

        buttonGroup7.add(violetActivated);
        violetActivated.setSelected(true);
        violetActivated.setText("Violet");

        buttonGroup7.add(violetDeactivated);
        violetDeactivated.setText("Violet");

        javax.swing.GroupLayout violetSwitchLayout = new javax.swing.GroupLayout(violetSwitch);
        violetSwitch.setLayout(violetSwitchLayout);
        violetSwitchLayout.setHorizontalGroup(
            violetSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(violetSwitchLayout.createSequentialGroup()
                .addComponent(violetActivated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(violetDeactivated, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        violetSwitchLayout.setVerticalGroup(
            violetSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(violetSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(violetActivated)
                .addComponent(violetDeactivated))
        );

        buttonGroup6.add(indegoActivated);
        indegoActivated.setSelected(true);
        indegoActivated.setText("Indego");

        buttonGroup6.add(indegoDeactivated);
        indegoDeactivated.setText("Indego");

        javax.swing.GroupLayout indegoSwitchLayout = new javax.swing.GroupLayout(indegoSwitch);
        indegoSwitch.setLayout(indegoSwitchLayout);
        indegoSwitchLayout.setHorizontalGroup(
            indegoSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indegoSwitchLayout.createSequentialGroup()
                .addComponent(indegoActivated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(indegoDeactivated, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        indegoSwitchLayout.setVerticalGroup(
            indegoSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indegoSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(indegoActivated)
                .addComponent(indegoDeactivated))
        );

        jTextField1.setEditable(false);
        jTextField1.setText("In                ||        Out");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jSlider1.setMinorTickSpacing(10);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);

        jSlider2.setMinorTickSpacing(10);
        jSlider2.setPaintTicks(true);
        jSlider2.setSnapToTicks(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item 1", "item 2", "item 3", "item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fileMenu.setText("File");
        fileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileMenuMouseClicked(evt);
            }
        });

        fileMenuLoad.setText("Load");
        fileMenu.add(fileMenuLoad);

        jMenuBar1.add(fileMenu);

        helpMenu.setText("Help");

        helpMenuCredits.setText("Credits");
        helpMenuCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuCreditsActionPerformed(evt);
            }
        });
        helpMenu.add(helpMenuCredits);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generateButton)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(redSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orangeSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yellowSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greenSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indegoSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(violetSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(redSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orangeSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yellowSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greenSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blueSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indegoSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(violetSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(generateButton)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        Dot.visibility(true);
    }//GEN-LAST:event_generateButtonActionPerformed

    private void fileMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuMouseClicked

    private void helpMenuCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMenuCreditsActionPerformed

    private void orangeActivatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeActivatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orangeActivatedActionPerformed

    private void greenActivatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActivatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenActivatedActionPerformed

    private void orangeDeactivatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeDeactivatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orangeDeactivatedActionPerformed

    private void greenDeactivatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenDeactivatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenDeactivatedActionPerformed

    private void redDeactivatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redDeactivatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redDeactivatedActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blueActivated;
    private javax.swing.JRadioButton blueDeactivated;
    private javax.swing.JPanel blueSwitch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileMenuLoad;
    private javax.swing.JButton generateButton;
    private javax.swing.JRadioButton greenActivated;
    private javax.swing.JRadioButton greenDeactivated;
    private javax.swing.JPanel greenSwitch;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuCredits;
    private javax.swing.JRadioButton indegoActivated;
    private javax.swing.JRadioButton indegoDeactivated;
    private javax.swing.JPanel indegoSwitch;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton orangeActivated;
    private javax.swing.JRadioButton orangeDeactivated;
    private javax.swing.JPanel orangeSwitch;
    private javax.swing.JRadioButton redActivated;
    private javax.swing.JRadioButton redDeactivated;
    private javax.swing.JPanel redSwitch;
    private javax.swing.JRadioButton violetActivated;
    private javax.swing.JRadioButton violetDeactivated;
    private javax.swing.JPanel violetSwitch;
    private javax.swing.JRadioButton yellowActivated;
    private javax.swing.JRadioButton yellowDeactivated;
    private javax.swing.JPanel yellowSwitch;
    // End of variables declaration//GEN-END:variables
}
